[unstable]
# Make binary size lots smaller:
build-std = ["std", "panic_abort"]
build-std-features = ["optimize_for_size"]

[build]
## Always make a statically-linked executable
#rustflags = [
#    "-Ctarget-feature=+crt-static",
#    "-Clink-self-contained=yes"
#]

# target = ["aarch64-unknown-linux-musl"]
